export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART ='REMOVE_FROM_CART';
export const UP_QUANTITY_CART = 'UP_QUANTITY_CART';
export const DOWN_QUANTITY_CART = 'DOWN_QUANTITY_CART';